#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
# displays username
# displays user id
# Home directory path for the user

input="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$input"
