#!/usr/bin/env bash
# displays 'bad luck' in the 4th iteration
# displays 'good luck' in the 8th iteration
# displays 'Best School' for other iterations

COUNTER=1
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 4 ]
    then
        echo "bad luck"
    elif [ $COUNTER = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((COUNTER++))
done
